// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// mwmoteCalcClusters
IntegerVector mwmoteCalcClusters(arma::mat distance_matrix, double threshold);
RcppExport SEXP _imbalance_mwmoteCalcClusters(SEXP distance_matrixSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type distance_matrix(distance_matrixSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(mwmoteCalcClusters(distance_matrix, threshold));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_imbalance_mwmoteCalcClusters", (DL_FUNC) &_imbalance_mwmoteCalcClusters, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_imbalance(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
