// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// racog_
NumericVector racog_(DataFrame dataset, IntegerMatrix edges, SEXP root, int iterations, int burnin, int lag);
RcppExport SEXP imbalance_racog_(SEXP datasetSEXP, SEXP edgesSEXP, SEXP rootSEXP, SEXP iterationsSEXP, SEXP burninSEXP, SEXP lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type dataset(datasetSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type edges(edgesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type root(rootSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    rcpp_result_gen = Rcpp::wrap(racog_(dataset, edges, root, iterations, burnin, lag));
    return rcpp_result_gen;
END_RCPP
}
