# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hClustering <- function(distance_matrix, threshold) {
    .Call(`_imbalance_hClustering`, distance_matrix, threshold)
}

computeGameProfiles <- function(probs, knn_neighbours, partial_payoffs, iterations, smooth_factor) {
    .Call(`_imbalance_computeGameProfiles`, probs, knn_neighbours, partial_payoffs, iterations, smooth_factor)
}

bestGaussianBandwidth <- function(dataset, covInv) {
    .Call(`_imbalance_bestGaussianBandwidth`, dataset, covInv)
}

